In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Assessors_Parcel_Data_2022.csv', low_memory=False)

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
data.head(5)

,PIN,ASMTYEAR,TAXYEAR,HOUSE_NO,STREET_NAME,UNIT_NO,ZIP_POSTAL,FORMATTED_ADDRESS,OWNERNM,TAXPAYER1,TAXPAYER2,TAXPAYER3,TAXPAYER4,PLAT_NO,NEIGHBORHOOD,COMMUNITY,WARD,ZONING,LANDUSE,PARCEL_AREA_SQFT,X,Y,PRIMARY_PROP_TYPE,LANDVALUE,BLDGVALUE,TOTALVALUE,IS_MULTIPLE_USES,IS_EXEMPT,IS_HOMESTEAD,SUB1_PT,SUB2_PT,SUB3_PT,SUB4_PT,SUB1_EXEMPTCD,SUB2_EXEMPTCD,SUB3_EXEMPTCD,SUB4_EXEMPTCD,NUM_BLDGS,BUILDINGUSE,YEARBUILT,BELOWGROUNDAREA,ABOVEGROUNDAREA,NUM_STORIES,NUM_GAR_STALLS,PRIMARYHEATING,CONSTRUCTIONTYPE,EXTERIORTYPE,ROOF,TOTAL_UNITS,FIREPLACES,BATHROOMS,BEDROOMS,FID
0,p0102824130046,2022,2023,3313,25TH AVE S,NaN,55406-2405,3313 25TH AVE S,ROBERT JOHN REICHGELD II,ROBERT JOHN REICHGELD II,3313 25TH AVE S,MINNEAPOLIS MN 55406,NaN,20330.0,CORCORAN,POWDERHORN,9,R1A,2 UNIT RESIDENTIAL - DUPLEX,4811.0,538269.127156,155189.821038,2 UNIT RESIDENTIAL,65000,227000,292000,NO,NOT EXEMPT,NON-HOMESTEADED,DB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,DUPLEX,1900.0,672,1648,2.0,2,FORCED AIR,WOOD FRAME,STUCCO,GABLE,2.0,0,2,2,1
1,p0102824130047,2022,2023,3317,25TH AVE S,NaN,55406-2405,3317 25TH AVE S,JLMPW HOLDINGS LLC,JLMPW HOLDINGS LLC,MATTHEW WAGNER,3317 25TH AVE S,MINNEAPOLIS MN 55406,20330.0,CORCORAN,POWDERHORN,9,R1A,2 UNIT RESIDENTIAL - DUPLEX,4424.0,538269.460887,155148.792185,2 UNIT RESIDENTIAL,73000,269000,342000,NO,NOT EXEMPT,NON-HOMESTEADED,DB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,DUPLEX,1962.0,1678,1678,1.0,2,FORCED AIR,WOOD FRAME,STUCCO,HIP,2.0,0,3,6,2
2,p0102824130048,2022,2023,3321,25TH AVE S,NaN,55406-2405,3321 25TH AVE S,CITY/LAKES COMMUNITY LAND TR,JACKSON J ARCOREN,TERESA E ARCOREN,3321 25TH AVE S,MINNEAPOLIS MN 55406,20330.0,CORCORAN,POWDERHORN,9,R1A,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,4424.0,538269.620689,155110.860945,RESIDENTIAL,24000,204000,228000,NO,NOT EXEMPT,NON-HOMESTEADED,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,SINGLE FAMILY HOUSE,2021.0,0,1323,1.5,2,NaN,WOOD FRAME,WOOD,GABLE,1.0,0,1,2,3
3,p0102824130049,2022,2023,3323,25TH AVE S,NaN,55406-2405,3323 25TH AVE S,TIMOTHY GODSILL,TIMOTHY GODSILL,6011 XERXES AVE S,MINNEAPOLIS MN 55410,NaN,20330.0,CORCORAN,POWDERHORN,9,R1A,2 UNIT RESIDENTIAL - DUPLEX,4424.0,538269.353581,155071.000502,2 UNIT RESIDENTIAL,73000,256000,329000,NO,NOT EXEMPT,NON-HOMESTEADED,DB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,DUPLEX,1962.0,1683,1692,1.0,0,FORCED AIR,WOOD FRAME,STUCCO,HIP,2.0,0,3,5,4
4,p0102824130050,2022,2023,3327,25TH AVE S,NaN,55406-2405,3327 25TH AVE S,BRANDON V CULBERSON,BRANDON V CULBERSON,3327 25TH AVE S,MINNEAPOLIS MN 55406,NaN,20330.0,CORCORAN,POWDERHORN,9,R1A,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,5530.0,538269.477518,155025.357914,RESIDENTIAL,83000,236000,319000,NO,NOT EXEMPT,HOMESTEADED,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,SINGLE FAMILY HOUSE,1925.0,1188,1563,1.2,2,FORCED AIR,WOOD FRAME,STUCCO,GABLE,1.0,0,2,4,5

In [6]:
df = data[['X','Y','WARD','LANDVALUE','BLDGVALUE','TOTALVALUE','LANDUSE','PARCEL_AREA_SQFT','BUILDINGUSE','YEARBUILT']]

In [8]:
df.head(50)

,X,Y,WARD,LANDVALUE,BLDGVALUE,TOTALVALUE,LANDUSE,PARCEL_AREA_SQFT,BUILDINGUSE,YEARBUILT
0,538269.127156,155189.821038,9,65000,227000,292000,2 UNIT RESIDENTIAL - DUPLEX,4811.0,DUPLEX,1900.0
1,538269.460887,155148.792185,9,73000,269000,342000,2 UNIT RESIDENTIAL - DUPLEX,4424.0,DUPLEX,1962.0
2,538269.620689,155110.860945,9,24000,204000,228000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,4424.0,SINGLE FAMILY HOUSE,2021.0
3,538269.353581,155071.000502,9,73000,256000,329000,2 UNIT RESIDENTIAL - DUPLEX,4424.0,DUPLEX,1962.0
4,538269.477518,155025.357914,9,83000,236000,319000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,5530.0,SINGLE FAMILY HOUSE,1925.0
5,538269.828595,154974.577650,9,83000,175000,258000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,5530.0,SINGLE FAMILY HOUSE,1915.0
6,538269.769986,154923.584633,9,83000,175000,258000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,5530.0,SINGLE FAMILY HOUSE,1952.0
7,538270.170461,154874.346506,9,82000,215000,297000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,5452.0,SINGLE FAMILY HOUSE,1915.0
8,537943.438134,155074.389970,9,90000,186000,276000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,6843.0,SINGLE FAMILY HOUSE,1908.0
9,537943.330579,155024.528258,9,95000,88000,183000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,6843.0,SINGLE FAMILY HOUSE,1912.0
10,537943.209708,154973.448753,9,95000,134000,229000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,6843.0,SINGLE FAMILY HOUSE,1912.0
11,537943.326981,154922.293864,9,95000,255000,350000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,6843.0,SINGLE FAMILY HOUSE,1940.0
12,537944.057684,154873.027903,9,94000,190000,284000,2 UNIT RESIDENTIAL - DUPLEX,6748.0,DUPLEX,1900.0
13,538088.437882,154873.645559,9,87000,309000,396000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,6263.0,SINGLE FAMILY HOUSE,1918.0
14,538088.332292,154922.834498,9,88000,187000,275000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,6348.0,SINGLE FAMILY HOUSE,1916.0
15,538088.508532,154973.542731,9,88000,274000,362000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,6348.0,SINGLE FAMILY HOUSE,1914.0
16,538088.132007,155024.204715,9,88000,178000,266000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,6348.0,SINGLE FAMILY HOUSE,1915.0
17,538087.940248,155074.337358,9,88000,192000,280000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,6348.0,SINGLE FAMILY HOUSE,1926.0
18,538087.681753,155123.578992,9,101600,382900,484500,MULTI-FAMILY APARTMENT,6350.0,APARTMENT 4 OR 5 UNIT,1915.0
19,538088.440990,155168.729015,9,82000,251000,333000,2 UNIT RESIDENTIAL - DUPLEX,5333.0,DUPLEX,1914.0
20,538985.670672,155976.270608,9,173000,547000,720000,"IND WAREHOUSE, FACTORY OR WORKSHOP",13306.0,WORKSHOP,1972.0
21,537942.836140,155232.644097,9,247200,867800,1115000,UTILITY,35933.0,TELEPHONE EXCHANGE,1982.0
22,539064.773643,155848.045729,9,234000,796000,1030000,"IND WAREHOUSE, FACTORY OR WORKSHOP",18000.0,INDUSTRIAL WORKSHOP,1970.0
23,538813.505260,155719.306939,9,1685800,798200,2484000,"IND WAREHOUSE, FACTORY OR WORKSHOP",172900.0,WAREHOUSE,1917.0
24,539080.371889,155307.731200,9,227300,242700,470000,"IND WAREHOUSE, FACTORY OR WORKSHOP",17488.0,WORKSHOP,1968.0
25,539003.744367,155226.524221,9,607100,909900,1517000,"IND WAREHOUSE, FACTORY OR WORKSHOP",46698.0,WAREHOUSE,1986.0
26,539108.360503,154978.169776,9,534500,142500,677000,UTILITY,45684.0,TELEPHONE EXCHANGE,1999.0
27,538712.725960,155269.343739,9,502300,188700,691000,VEHICLE RELATED USE,31395.0,SERV. STATION W/STORE,1989.0
28,538609.750000,155356.484375,9,0,0,0,VACANT,780.0,NaN,NaN
29,538087.915937,155210.871662,9,80000,157000,237000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,5079.0,SINGLE FAMILY HOUSE,1905.0
30,538087.665453,155254.278688,9,82000,237000,319000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,5333.0,SINGLE FAMILY HOUSE,1993.0
31,538087.690549,155298.469717,9,82000,239000,321000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,5330.0,SINGLE FAMILY HOUSE,1993.0
32,538087.727155,155342.969363,9,85000,255000,340000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,5824.0,SINGLE FAMILY HOUSE,1993.0
33,539120.422322,155742.438279,9,76600,313400,390000,"IND WAREHOUSE, FACTORY OR WORKSHOP",5889.0,WORKSHOP,1974.0
34,539139.428362,155707.045101,9,76900,281100,358000,"IND WAREHOUSE, FACTORY OR WORKSHOP",5913.0,WORKSHOP,1973.0
35,537944.185784,155942.007387,9,94000,232000,326000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,7597.0,SINGLE FAMILY HOUSE,1994.0
36,538268.893540,155338.487762,9,72000,245000,317000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,5965.0,SINGLE FAMILY HOUSE,1995.0
37,537937.312825,155856.221878,9,108000,205000,313000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,10716.0,SINGLE FAMILY HOUSE,1900.0
38,537941.888747,155793.933922,9,87000,141000,228000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,6273.0,SINGLE FAMILY HOUSE,1923.0
39,538101.747064,155478.521496,9,128000,379000,507000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,16870.0,SINGLE FAMILY HOUSE,1997.0
40,538093.123158,155704.074575,9,842500,421800,1264300,MULTI-FAMILY RESIDENTIAL,52655.0,APARTMENT 4 OR 5 UNIT,2007.0
41,537978.705358,155980.973436,9,87000,257000,344000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,11139.0,SINGLE FAMILY HOUSE,1993.0
42,538255.050908,155282.391607,9,72000,113000,185000,1 UNIT RESIDENTIAL - SINGLE FAMILY HOUSE,5972.0,SINGLE FAMILY HOUSE,1915.0
43,538339.946430,155108.154620,9,11500,0,11500,VACANT,3074.0,NaN,NaN
44,538435.379861,155025.666683,9,9000,198000,207000,1 UNIT RESIDENTIAL - CONDOMINIUM,73059.0,CONDOMINIUM,2004.0
45,538435.379861,155025.666683,9,10200,146800,157000,1 UNIT RESIDENTIAL - CONDOMINIUM,73059.0,CONDOMINIUM,2004.0
46,538435.379861,155025.666683,9,10700,200300,211000,1 UNIT RESIDENTIAL - CONDOMINIUM,73059.0,CONDOMINIUM,2004.0
47,538435.379861,155025.666683,9,10200,182800,193000,1 UNIT RESIDENTIAL - CONDOMINIUM,73059.0,CONDOMINIUM,2004.0
48,538435.379861,155025.666683,9,10700,181300,192000,1 UNIT RESIDENTIAL - CONDOMINIUM,73059.0,CONDOMINIUM,2004.0
49,538435.379861,155025.666683,9,10700,164300,175000,1 UNIT RESIDENTIAL - CONDOMINIUM,73059.0,CONDOMINIUM,2004.0

In [24]:
df['TOTALVALUE'].cumsum()

0              292000
1              634000
2              862000
3             1191000
4             1510000
             ...
130767    64573420100
130768    64573520100
130769    64573772100
130770    64574022100
130771    64574292100
Name: TOTALVALUE, Length: 130772, dtype: int64